### ISSUE TITLE
Editor (editor-0.8.26.js) doesn't work in Safari 9.1 (11601.5.17.1) under MacOS El Capitan

### ISSUE THREAD

**Issue by Marvel77** [filearts/plunker#111]
Hi guys!

It seems there is some issue with editor. It doesn't work since yesterday, if there were any updates?

Screenshots are attached

Editor is shadowed and it's script execution is stopped.
![2016-05-17 10 38 29](https://cloud.githubusercontent.com/assets/11765873/15311398/952f735e-1c24-11e6-9367-61a37e899398.png)

And there is some error in the debugger
![2016-05-17 10 42 48](https://cloud.githubusercontent.com/assets/11765873/15311413/b174aff2-1c24-11e6-8aa0-a84926bd8c28.png)

In Chrome it works perfectly.

**Comment by anthonyko** [comment]
I'm running into the same problem with Safari.

**Comment by Marvel77** [comment]
whatever..
