### ISSUE TITLE
What is the difference between Private or Public Plunk

### ISSUE THREAD

**Issue by temmyg** [filearts/plunker#116]
I see if I save a Plunk as public, it just has the url with less characters(only 5 instead of long chars) and also the tips said "Everyone can see this Plunk", while if I save it as private, the tips said "Only users who know the url of the plunk will be able to view it". 

I wonder what is the difference between these two options, it seems for public plunk I still need to share the url with another person for him to access and except that, there is no other way to access this plunk, Am I right?

**Comment by ggoodman** [comment]
@temmyg the only real difference is whether or not the plunk will appear to other users in your user profile and in the public plunk listings. A better name for this feature would have been 'secret plunk'.
