### ISSUE TITLE
Site never opens code examples, always makes redirects to http://plnkr.co/edit/?p=preview

### ISSUE THREAD

**Issue by wzup** [filearts/plunker#118]
How see code example? Your site always makes redirects to http://plnkr.co/edit/?p=preview.

For example, here are some links from Paypal docs. And I cannot see anyone because of the redirects!

http://plnkr.co/edit/2GGEyNEFUPCZ7jIIGk9X?p=preview
http://plnkr.co/edit/XS7EvmrCY1UlkF1nHe8x?p=preview
http://plnkr.co/edit/RifUli3hDIq6kQJI0Ujc?p=preview
http://plnkr.co/edit/2xZbf7YATgldHklUPMXq?p=preview

When I follow the link (any link, not only those above) your site always redirects to http://plnkr.co/edit/?p=preview

Why? How does your fantastic futuristic appliance work?

**Comment by wzup** [comment]
Incidentally! I already asked the question before https://github.com/filearts/plunker/issues/105. 
8 months and no answer. Representative.

**Comment by ggoodman** [comment]
Hi @wzup. Those links all work for me in the latest version of Chrome, Safari and Firefox. I do not have access to IE / Edge to test.

The 8 month period without answer is only representative of one thing: I'm alone in building this free service and have other time commitments. You could have spent that time investigating and proposing a fix to the bug given that the whole platform is open-source.
