### ISSUE TITLE
'X-Frame-Options' to 'SAMEORIGIN' issue

### ISSUE THREAD

**Issue by adibwoy** [filearts/plunker#119]
When I try to access this plunk: https://plnkr.co/edit/ONGeKcu0sVfQqR7gpHZY?p=preview I get this issue:

Refused to display 'https://run.plnkr.co/dBfboyNnXcdsgXwH/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

Does anyone know why?

**Comment by hmoritz** [comment]
I have the same issue in Chrome Version 53 (Windows 10).
I switched to Firefox but after some time I got the error message 'Load denied by X-Frame-Options: https://run.plnkr.co/AfS9gqrHH7Q7ini6/ does not permit cross-origin framing.'

**Comment by ggoodman** [comment]
@adityarb88 @hmoritz there was an unusual level of traffic lately that put abnormal strain on the service that runs previews. This service had several hiccups that manifest themselves as the errors you two have noticed.

I rewrote a portion of the run service to support horizontal scalability by externalizing previews from in-memory caches to redis in ggoodman/plunker-run@badb2260b88b85419ca37c6912d0b10701686686. This service is now running as 3 instances across 2 nodes.

Please let me know if you continue to see issues.
