### ISSUE TITLE
plnkr.co is down

### ISSUE THREAD

**Issue by Hintalo** [filearts/plunker#120]
Currently I get the following error message if I go to www.plnkr.co:
"NO APPLICATION WAS FOUND FOR plnkr.co".
None of the plunker URLs work at this time (http://plnkr.co/edit/xxxxx?p=preview).
Can you please check it.
Thanks.

**Comment by ggoodman** [comment]
Like many, much larger sites, Plunker was affected by the DDoS attack on Dyn (see: http://dyn.com/blog/dyn-statement-on-10212016-ddos-attack/). Now that Dyn is back to business, Plunker's service is restored.
