### ISSUE TITLE
Missing ng-app from template

### ISSUE THREAD

**Issue by lolaswift** [filearts/plunker#133]
When creating a new angularjs 1.5.x & 1.4.x project from template,
ng-app is missing from the index html file. Therefore, it only displays:
hello {{name}}! on the view.

**Comment by gkalpak** [comment]
I works as expected for me (fwiw). `ngApp` is there.

**Comment by lolaswift** [comment]
Yes, it's working for me as well. I guessed someone has fixed it silently :-)
