### ISSUE TITLE
plunker embed has weird square brackets

### ISSUE THREAD

**Issue by sag1v** [filearts/plunker#136]
I got some weird square brackets:
chrome Version 59.0.3071.115 (Official Build) (64-bit) (win7)
![plnkr1](https://user-images.githubusercontent.com/9153149/29632908-180f568c-884d-11e7-87c9-5f3fd92c29e1.jpg)

**UPDATE:**
I've noticed it renders this `div`:
`<div class="ace_bracket ace_start ace_br15" style="height:27px;width:12.645625px;top:162px;left:4px;"></div>`

and this is the styling for it:
```
.ace-monokai .ace_marker-layer .ace_bracket {
    margin: -1px 0 0 -1px;
    border: 1px solid #49483E;
}
```
The problem is that theres no brackets in this specific spot hence it renders it for no reason.
I have checked it in fire fox and it looks ok. 
After i save the plunk (going to the regular plunker editor) and re-open the embed editor it looks fine until i try to edit again.

**UPDATE 2** 
I'm not sure but i think it has something to do with copy - paste.
When i copy paste code to the editor it happens, but when i'm not it seems to be ok.

**Comment by ggoodman** [comment]
Hey big thanks for sharing and for finding the specific manifestation of this bug. I've also seen this in the wild. Until now, I hadn't thought much of it, but your bug report allowed me to track down the culprit 👍 .

I've traced the issue to what appears to be a bug with the editor component that Plunker uses (see: ajaxorg/ace#3392). If I'm unable to have this resolved upstream, I will try and figure out a way to get a patch integrated without making future maintenance impossible.

**Comment by sag1v** [comment]
I'm glad you found out the source for this. 
In the meanwhile, i'm using the embed version just because its supporting folders and it helps me demonstrate the code to other developers. is there any way i can get the same structure view of files and folders with the regular plunker editor? now it just shows the files with the folder name chained together. ie: `folderName.filename.extention`

**Comment by sag1v** [comment]
@ggoodman see my update regarding copy-paste

**Comment by ggoodman** [comment]
Thanks for the update. For a better editing experience, can you try https://next.plnkr.co and let me know what you think?

**Comment by sag1v** [comment]
looks nice, it still has that bug i mentioned but the experience is nicer as it kinda combine the benefits of the main editor with save capabilities and the folder support that the embed editor has. i'm going to keep using it. hope it's safe to use, i have a code presentation to do next week :)

**Comment by ggoodman** [comment]
@sag1v it should be safe to use :).

**Comment by ggoodman** [comment]
This is now fixed in the `embed` and `next` is deploying.

**Comment by jyoti122** [comment]
OK Thank you so much...
