### ISSUE TITLE
Embed view saving  as html entities

### ISSUE THREAD

**Issue by magnumjs** [filearts/plunker#139]
How to reproduce:

Go to any plunker at the homepage:
https://plnkr.co/

Click the embed view link:
https://embed.plnkr.co/9TvHuv/

All files with these characters < > now have their HTML entities `&lt;` `&gt;` even if you click back to the editor view.

https://plnkr.co/edit/9TvHuv?p=info

If you are the owner of that PLUNK it will also automatically save it that way.

**Comment by ggoodman** [comment]
Thanks for reporting. This issue is now fixed in production.

**Comment by erwanv** [comment]
It fixes the HTML problem indeed but another issue seems to be remaining, see:
https://github.com/filearts/plunker/issues/140

Thank you for your awesome work!
