### ISSUE TITLE
Download your Plunk as a zip file is not working

### ISSUE THREAD

**Issue by gsans** [filearts/plunker#141]
I have tried using any of my latest Plunks and also using an empty template for "Angular" with no luck. All zip files downloaded are empty.

**Comment by ggoodman** [comment]
Hi @gsans, can you provide some details on which browser you're using and from which url / interface your are seeing this issue?

**Comment by gsans** [comment]
Sure. I've tried both in Chrome (Version 60.0.3112.113) an Firefox (52.3.0). I initially tried with my own projects but the default Angular template is already not working.

**Comment by ggoodman** [comment]
@gsans I'm finding it impossible to reproduce this issue in Chrome (61.0.3163.100) and Firefox (50.1.0) on MacOS 10.12.6. Are there any common extensions set up in your browsers? Are you running on another OS?

**Comment by gsans** [comment]
I just checked again and now it's working both for Chrome and Firefox...
Not sure what was happening.

I wanted to use this for a workshop yesterday at Angular Summit Boston and
didn't worked. Maybe a temporary network issue? Thanks!

**Comment by ggoodman** [comment]
Hi @gsans, a network issue would be a very unlikely cause. The download feature doesn't actually generate any network requests and is done entirely client-side.

Closing but please let me know if you are able to reproduce in the future. I hope that this didn't cause undue problems in your workshop. You might consider https://next.plnkr.co for the time being as that is where active development is happening.
