### ISSUE TITLE
Unable to login with Github

### ISSUE THREAD

**Issue by pjcat** [filearts/plunker#150]
'I'm attempting to login via my Github account and am just receiving the Login Error - Undefined" message.  I saw this issue has popped up in the past with other users so I tried both http and https as noted in those threads, with no success.  In GitHub I do see Plnkr as an authorized OAuth app.  Any ideas?

**Comment by ggoodman** [comment]
Hello @pjcat, I've found that due to a bug in the plunker.next api, your user profile (and several others who had signed in during the same period of time last year) had been put in an inconsistent state. This should now be fixed. Please let me know if that is not the case and I will reopen.
