### ISSUE TITLE
My plunk has been deleted

### ISSUE THREAD

**Issue by sundorf** [filearts/plunker#19]
I did a plunk with the number TtJC76. Today I wanted to send the link somebody but it seems to be gone. Ary plunks deleted automatically after a while?

**Comment by kousimca87** [comment]
@ggoodman

I have my private plunks. one of my plunk got deleted accidentally .  I don't have plunk number.

I was accessing the plunk in https://plnkr.co/edit/FcXqUd0J5n7QMXuklyOd?p=preview 

Now I can't see that plunk. Please help to recover that plunk.

**Comment by ggoodman** [comment]
@kousimca87 if you clicked 'Delete' and confirmed deletion, I am unable to recover your plunk.

**Comment by kousimca87** [comment]
Yes Goodman . I am new to angular js as well plunker. I was checking
versions of my plunk and pressed confirm deletion button accidentally. I
need to send that plunk. Is there any way to recover??.. Please suggest.


Thank you.

**Comment by meetvora2006** [comment]
@ggoodman Hi I accidentally deleted my plunk. it was at the given link.
https://plnkr.co/edit/uBqzY8GaRZUJrhKMDavh?p=info

after delete, I am not able to access it anyway. can you make it available to me again, please?
