### ISSUE TITLE
search plunks feature.

### ISSUE THREAD

**Issue by yahyaKacem** [filearts/plunker#43]
It will be awesome to add a search for plunks, it's painful to go through all those plunks to find a plunk I wrote 3 or 4 months ago.
Maybe search by tags and search by title.
Thanks for such a great tool anyway.

**Comment by ndejesus1227** [comment]
Is there still no ability to search for plunks I'd be interested in?????

**Comment by daixtrose** [comment]
:+1:

**Comment by daixtrose** [comment]
@ggoodman  In the meantime why not let google do the job? If plnkr.co would allow search engines to crawl the public items, this would be a great advantage.

**Comment by dumbrill** [comment]
👍   Hope it's coming soon.

**Comment by antonpegov** [comment]
When!?!

**Comment by RobbyDeLaet** [comment]
In 2013 we were waiting for MongoDB 2.6.
In 2014 is was "coming and it will be glorious"
Today, end of 2017, MongoDB is at version 3.6 and we are still waiting for this glorious moment...

**Comment by ggoodman** [comment]
@RobbyDeLaet: check out https://next.plnkr.co

Putting on the finishing touches before switching dns over. `mongo@3.6` is, indeed, a nice release. That being said, I went with ElasticSearch as a secondary datastore to provide search. Experiments with mongo `$text` and postgres text indices just didn't cut it.

Believe me, I want this to be out there more than you can imagine. I put a few hours in every single day but there are only 24 to work with.

**Comment by RobbyDeLaet** [comment]
@ggoodman I checked out the "next plnkr", nice job! Just one remark though, when you open a plunk, the "similar plunks" are taking half of the screen real-estate. Can you add a hide button?

I know the feeling of only having just 24 hours in a day. Keep up the nice work!

**Comment by ggoodman** [comment]
@RobbyDeLaet what size viewport are you using? I'm trying to make this screen useful across different viewport sizes but that is a bit of a tricky balancing act.

**Comment by RobbyDeLaet** [comment]
@ggoodman I was using 1903x1511 in Chrome on a 1920x1080 screen. I noticed that you did some changes because now [this page](https://next.plnkr.co/plunks/dVOwLJ) is displayed fine. The green blocks at the bottom are now visible without scrolling.

But the "similar plunks" are still taking half of the screen real-estate [see image](https://www.dropbox.com/s/nztj4wss0si753y/plnkr.png?dl=0). Perhaps make the top section a bit bigger, but keep the similar plunks visible at the bottom. Users can scroll down if they want to see them.

**Comment by ggoodman** [comment]
I've made a small tweak to the styling of that page and would love to hear your thoughts @RobbyDeLaet.

**Comment by RobbyDeLaet** [comment]
@ggoodman Yes that gives us a bit more space.

But... I noticed that there is a problem on the mobile view. When you open the page in a small desktop browser window, you get a vertical scrollbar in the "preview" section, which is nice. When I open the same page in Chrome on my iPhone, I don't get the vertical scrollbar and the text of the "preview" section floats over the "similar plunks" section. See [image](https://www.dropbox.com/s/qmf5d65s6rbiyek/iPhone.jpg?dl=0)

Thanks for all the efforts you put in plunkr.

**Comment by ggoodman** [comment]
Interesting. I'm on Android myself and this doesn't appear to happen. I don't have access to an iPhone to see this behaviour myself.

@RobbyDeLaet if you don't mind, can you share the url of the plunk that is displaying that behaviour?

> Thanks for all the efforts you put in plunkr.

Thanks for saying so 😄 !

**Comment by RobbyDeLaet** [comment]
It was in the comment of this morning (for me at least) 😄 https://next.plnkr.co/plunks/dVOwLJ

**Comment by ggoodman** [comment]
Hi @RobbyDeLaet, guess I missed that. I've added `overflow: hidden` to the wrapper element hosting the preview `iframe`. Can you let me know if this eliminates the craziness you were seeing?

**Comment by RobbyDeLaet** [comment]
@ggoodman much better indeed, but still no vertical scrollbar on the "preview" section.

**Comment by kyoz** [comment]
Thanks @RobbyDeLaet for your hard work to created some awesome thing like this. btw at the moment, i'm using next plnkr, so is all my plunks still there or everything will be delete when it actually release ?. Thank you so much :smile:

**Comment by RobbyDeLaet** [comment]
Hi @banminkyoz I'm just a Plnkr user like you. All credits go to @ggoodman who is the creator of this fantastic software.

**Comment by kyoz** [comment]
Lol...Wrong tag..haha. sorry so much @ggoodman  :laughing:

**Comment by ggoodman** [comment]
> everything will be delete when it actually release ?

@banminkyoz the plunks in both next.plnkr.co and plnkr.co are stored in the same place in the same format. Your plunks therefore don't need migration! 🎉
