### ISSUE TITLE
Keyboard shortcut for refreshing preview?

### ISSUE THREAD

**Issue by tedyoung** [filearts/plunker#61]
I don't see a keyboard shortcut for refreshing the view (I've turned off auto-refresh because it tends to be too eager to update even while I'm typing). I see that Ctrl+Enter will turn the preview pane on and off, but I don't see anything that will do the same thing as clicking the refresh button.

I'm guessing that adding a new command to https://github.com/filearts/plunker_www/blob/master/assets/js/directives/ace.coffee would do the job, but it's unclear to me (I'm still new to Angular) how I'd call the refresh() function in plunks.coffee (the one that's called from previewer.coffee line 53).

**Comment by jonataswalker** [comment]
This will be a great shortcut. +1

**Comment by agraebe** [comment]
:+1:

**Comment by ggoodman** [comment]
Plunker.NEXT has separate hotkeys to toggle the preview pane and to trigger a preview re-render. I'm, unfortunately, not going to invest time in this land of dragons and coffee-script that is in this repo and in production.
