### ISSUE TITLE
Loading... plunker is not accessible

### ISSUE THREAD

**Issue by blackat** [filearts/plunker#79]
Hi,
when I browse to plunkr I get the home page with the "Loading..." message and dark background, unfortunately it doesn't disappear, it seems stuck!

I cannot select any kind of functionality, I have tried with Chrome and Firefox. In the Chrome console I get the following error
GET http://api.plnkr.co/proxy.html 503 (Service Unavailable)

DO you have any idea?

**Comment by blackat** [comment]
It seems back with some errors
Uncaught TypeError: undefined is not a function
http://shot.plunker.co/W59Vy1.png?d=2015-01-29T12:29:05.350Z Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by ggoodman** [comment]
Having some issues with hosting. Seems to be mostly resolved.

**Comment by blackat** [comment]
Thanks a lot for your quick answer, you're doing a great job :-)

**Comment by tonylampada** [comment]
it seems to be down today again

**Comment by Stiino0** [comment]
Good day,

Are there still issues with the website like a couple of times a day? Or am I doing something wrong? Homepage keeps LOADING... in middle of screen, no way to log in or look at plunks...

![image](https://cloud.githubusercontent.com/assets/11710334/9839005/f92ad1d4-5a6c-11e5-8302-1e45b7c61821.png)

Thanks for any help regarding this issue.

**Comment by ggoodman** [comment]
The api instance on AppEngine decided that it no longer had the will to hang on and took an unexpected leave yesterday and never returned.

I've updated the AppEngine configuration and re-deployed. Things should be back to normal now.

**Comment by Stiino0** [comment]
Seems to work fine now! Thanks.

**Comment by vinamramattoo** [comment]
its still stuck on loading. i can access the  edit  using the url but not through the  home page

**Comment by RodrigoMattosoSilveira** [comment]
I'm having the same problem ... Worked fine until late Sunday evening ... I have not been able to access it since Monday Morning. A colleague of mine did not experience the same.

**Comment by RodrigoMattosoSilveira** [comment]
The problem above was fixed by removing related cookies!
