### ISSUE TITLE
Templates Bugged

### ISSUE THREAD

**Issue by SimeonC** [filearts/plunker#82]
I created a new template the other day and tried to use it, but it won't load.
http://plnkr.co/edit/tpl:8G84wkJVjabOvCl1DryF.
Original plunker: http://plnkr.co/edit/8G84wkJVjabOvCl1DryF?p=info
A bunch of errors appear like this:
```
[Error] TypeError: undefined is not a function (evaluating 'e.data.match(/at\-share\-bookmarklet\:(.+?)$/)')	(anonymous function) (core201.js, line 3)
```

Any idea why this is happening?

**Comment by ggoodman** [comment]
Those ridiculous number of errors come from the addthis embeds on plunker.
I'm really starting to question their value. As to your template issue it
seems that you're requiring textAngular `1.3.x` when the catalogue only has
a `1.2.x` version.

I realize that there should be some **intelligent** error handling to
prevent a total fail like this and am working on that as a part of
Plunker.NEXT. Change that `data-require="textAngular@1.3.x"` to
`data-require="textAngular@1.2.x"` or add a newer version of textAngular to
the package catalogue.

**Comment by SimeonC** [comment]
Ah, ok. Thanks for the quick reply, turns out I can also fix this by just removing the 'data-require' field...
