### ISSUE TITLE
Option to disable linting in order to support es6/7 features

### ISSUE THREAD

**Issue by Aaike** [filearts/plunker#87]
I've put together a plunk of the Aurelia navigation skeleton : http://plnkr.co/edit/uNVEk2

It uses jspm/babel to transpile es6/7 features.
However some features like decorators are not supported yet with jshint, so i have to add a //jshint ignore:true at the end of each line that jshint doesn't support yet.

If i don't do that and ignore the linting then the files do not get served by plunker...

Is there a way to disable linting for all files of a paricular plunk ? That would make it much easier for now to use es/7 features.

**Comment by ericelliott** [comment]
:+1: 

Even better - let us use custom lint config.

**Comment by ggoodman** [comment]
There shouldn't be any reason that changing the linting options would affect plunker's ability to serve files. Perhaps this affects babel's treatment of these files.

I'm no babel expert but for those of you with experience, here is the code that transforms `.6to5.js` files into `.js` files: https://github.com/ggoodman/plunker-run-plugin/blob/master/adapters/transformers/6to5.js And `.es6.js` files into `.js` files: https://github.com/ggoodman/plunker-run-plugin/blob/master/adapters/transformers/es6.js

Bother are quite naive, simple translations. Are there any compiler flags for these libs (or conventions regarding these) to change the behaviour during compilation?

**Comment by Aaike** [comment]
The linting does indeed not interfere with the compiling after all. The plunkers are working just fine with the lint errors

For babel experimental features can be enabled using the stage or the optional property : http://babeljs.io/docs/usage/experimental/

**Comment by ericelliott** [comment]
Can we just treat all .js files like ES6+ w/Babel and use ESLint? ES6 is the current recommended JavaScript spec. =)

See [How to Use ES6 for Universal JavaScript](https://medium.com/javascript-scene/how-to-use-es6-for-isomorphic-javascript-apps-2a9c3abe5ea2), and [prod-module-boilerplate](https://github.com/cloverfield-tools/prod-module-boilerplate).

**Comment by ggoodman** [comment]
I'm working on a nice ES6 compilation solution. As to linting, that needs
to be added to ACE and I don't have the bandwidth for that these days.

Geoff

**Comment by ericelliott** [comment]
:+1:

**Comment by Aaike** [comment]
Note that there is also babel lint , that seems to work the best for now : https://github.com/babel/babel-eslint

**Comment by ericelliott** [comment]
That may be a good temporary solution. Long-term lint config should be user configurable.

**Comment by ggoodman** [comment]
I've re-written the ggoodman/plunker-run-plugin to support a new method of invoking compilation:

* You can now use standard `.js` files but add the directive `"use traceur";` or `"use babel";` to cause those files to be passed through the respective compilers.
* You can also pass options to these compilers with the following syntax: `"use babel({stage: 0})"` for when you would like to use settings that are not part of the default behaviour of these compilers.


What do you think? Let me know how it works for you.

**Comment by ericelliott** [comment]
@ggoodman

> I've re-written the ggoodman/plunker-run-plugin to support a new method of invoking compilation:

Cool. Have you documented where / how to do this configuration?

**Comment by ggoodman** [comment]
I have not. Unfortunately, I don't really have any documentation. Those directives are to be put on the first line of your `.js` files. The actual directive will be stripped out (but not the newline).

Example:

**script.js**:

```javascript
"use babel({stage: 0})";

$(() => {
  console.log('Yay for fat arrows');
});
```

**Comment by ericelliott** [comment]
That's awkward. My JS files are examples for a JavaScript course. Can't config options like this be sourced from configuration files, instead?

**Comment by ggoodman** [comment]
What is the industry standard for holding this type of configuration file (babel, traceur, etc...). Linting is another discussion but it would be nice to know how that is configured as well.

**Comment by ericelliott** [comment]
[`.babelrc`](https://github.com/cloverfield-tools/prod-module-boilerplate/blob/master/.babelrc) & [`.eslintrc`](https://github.com/cloverfield-tools/prod-module-boilerplate/blob/master/.eslintrc) are the standard ways to configure babel & ESLint, respectively. I haven't heard of anybody using traceur lately. I don't know the best way to configure it.

You could have a custom `plunker` config key in `package.json` and use that to configure anything you want...

**Comment by ggoodman** [comment]
I've updated the run server to read the file `.babelrc` in the current plunk and apply the configuration options therein to babel when compiling `.babel.js`, `.6to5.js` and `.jsx` to `.js` (also applies with the `"use babel";` directive in a normal `.js` file).

This should fit pretty well with normal practices. Let me know what you think.

**Comment by ericelliott** [comment]
:+1:
