### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by KyleMit** [filearts/plunker#89]
Don't know if this is the correct place for downtime bugs, but I'm getting 500 errors for all the png resources in plunker.  Here's the network tab from loading the main page

![network tab](http://i.imgur.com/8prwjvb.png)

I'm on Windows 7; Chrome 43.0.2357.81 m

**Comment by ggoodman** [comment]
Restarted the webshot server that periodically blows memory limits due to phantomjs. Closed.
