### ISSUE TITLE
Babel ES6 + ESLint

### ISSUE THREAD

**Issue by ericelliott** [filearts/plunker#91]
I'm teaching courses on ES6, and I'd love to have interactive, embeddable examples and exercises using plunker.

Is there a way to configure it to use ES6, Babel, and ESLint (I need special lint rules)?

**Comment by PhiLhoSoft** [comment]
Not sure why you hadn't an answer (busy devs?), but while I was asking myself the same question, I did a simple search, and your question was on top of the list...
And, just below, I saw this tweet posted 5 days later: https://twitter.com/plnkrco/status/621326054020521984
It works: http://plnkr.co/edit/TU9fA4?p=preview

To repeat the information here, the content of the tweet is:

> ES6 user? Just add "use babel"; or "use traceur"; to the top of your .js files. Configure the compilers with .babelrc and .traceurrc.
Perhaps it supports ESLint configuration this way? I haven't tried yet.

**Comment by ggoodman** [comment]
Hi @PhiLhoSoft @ericelliott yes, this is a case of busy developer syndrome.

I created a detailed explanation of using different compilers in plunker here: http://embed.plnkr.co/suu7Yg/preview

**Comment by PhiLhoSoft** [comment]
Do you a similar page about linters? I want to suppress some spurious warnings, like "no adjacent classes" in CSS (I don't target old browsers).

**Comment by ggoodman** [comment]
Alas no. I have not done anything to customize the behaviour of the default
jsHint included in the ace editor.
