### ISSUE TITLE
npm installation issue

### ISSUE THREAD

**Issue by madhurangaonbit** [filearts/plunker#92]
When run npm install some errors are found,

> kerberos@0.0.4 install /usr/local/lib/node_modules/plunker/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-
> bson@0.2.22 install /usr/local/lib/node_modules/plunker/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

Could you check it?

**Comment by ggoodman** [comment]
These errors are normal if you are trying to install anything that depends on MongoDB in an environment where the `node-gyp` isn't able to compile optional binary modules.

**Comment by madhurangaonbit** [comment]
What we can do to solve it ?

**Comment by ggoodman** [comment]
Is this preventing you from doing `npm install`?
