### ISSUE TITLE
Feature request -- syntax checking, especially JS

### ISSUE THREAD

**Issue by abalter** [filearts/plunker#94]
Please consider including some syntax validation, particularly JS. I often choose to use JSFiddle because it checks my Javascript.

**Comment by abalter** [comment]
Duh. I found it.

**Comment by zoechi** [comment]
where did you find it?

**Comment by ggoodman** [comment]
Checkmark button in the toolbar.

**Comment by zoechi** [comment]
Doesn't show JS syntax errors for me. I have to stick with dev console then.

**Comment by ggoodman** [comment]
For syntax errors, you should see this: 
![image](https://cloud.githubusercontent.com/assets/50030/11033702/4b467e60-86b3-11e5-8d08-b7189790c5e5.png)
